name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            👋 @{{ author }},
            
            Thank you for raising this issue. We will investigate and get back to you as soon as possible.
            
            Please make sure you have given us as much context as possible.
          pullRequestOpened: >
            👋 @{{ author }},
            
            Thank you for raising this pull request 💙.
            
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible. 
